name: SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest  # Changed to Linux for macOS compatibility

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for SonarQube PR analysis

      - name: Install .NET and SonarScanner
        run: |
          dotnet tool install --global dotnet-sonarscanner  # Install scanner globally
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH  # Ensure global tools are in PATH

      - name: Build and analyze with SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd sem5pi/mdr  # Move to the correct directory
          dotnet-sonarscanner begin /k:"ruivieira03_Projeto-Estagio-Teste" /o:"ruivieira03" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build  # Build the project
          dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
