name: SonarQube JS Analysis

on:
  push:
    branches:
      - main
      - js
    paths:
      - 'sem5pi/SPA/**'  # Only trigger SonarQube JS analysis when files in sem5pi/SPA change
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - js
    paths:
      - 'sem5pi/SPA/**'  # Only trigger SonarQube JS analysis when files in sem5pi/SPA change

jobs:
  sonarqube-js:
    name: SonarQube JS Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Reinstall dependencies
        working-directory: sem5pi/SPA
        run: |
          npm install
          npm install react-router-dom@6.28.0

      - name: Run tests and generate coverage report
        working-directory: sem5pi/SPA
        run: |
          # Run Jest tests with coverage flag to generate LCOV report
          npm test -- --coverage --coverageReporters=text-lcov > coverage.lcov

      - name: SonarQube Scan (JS)
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          project-root: sem5pi/SPA  # Specify JS directory
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # Add the path to your LCOV file for SonarQube to include the coverage
          SONAR_SCANNER_PARAMS: |
            -Dsonar.javascript.lcov.reportPaths=coverage.lcov
