name: SonarQube .NET Analysis

on:
  push:
    branches:
      - main
      - dotnet
    paths:
      - 'sem5pi/MDR/**'  # Only trigger SonarQube .NET analysis when files in sem5pi/MDR change
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - dotnet
    paths:
      - 'sem5pi/MDR/**'  # Only trigger SonarQube .NET analysis when files in sem5pi/MDR change

jobs:
  sonarqube-dotnet:
    name: SonarQube .NET Analysis
    runs-on: macos-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x'
      - name: Install SonarScanner tool
        run: dotnet tool install --global dotnet-sonarscanner
      - name: Install ReportGenerator
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
      - name: Install dotnet-coverage
        run: |
          dotnet tool install --global dotnet-coverage
      - name: Run SonarScanner analysis with test coverage
        run: |
          working-directory: sem5pi/MDR
          dotnet sonarscanner begin /k:"ruivieira03_Projeto-Estagio-Teste" /o:"ruivieira03" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.vscoveragexml.reportsPaths="coverage.xml"

          dotnet test --collect:"XPlat Code Coverage"
          dotnet build sem5pi-24-25-g034.sln --no-incremental
          dotnet test sem5pi-24-25-g034.sln --collect:"Code Coverage" --settings ./coverlet.runsettings

          reportgenerator \
            -reports:coverage.xml \
            -targetdir:coverage-report \
            -reporttypes:Cobertura
          dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
